# Generated by Django 4.2 on 2023-04-21 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userskill_userprofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userskill",
            old_name="skill",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skills",
                related_query_name="skill",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
