# Generated by Django 4.2 on 2023-04-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_userprofile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
