# Generated by Django 4.2 on 2023-04-21 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectmemberreview",
            old_name="review",
            new_name="text",
        ),
    ]
