# Generated by Django 4.2 on 2023-04-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_rename_review_projectmemberreview_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmemberreview",
            name="headline",
            field=models.CharField(default="hello", max_length=100),
            preserve_default=False,
        ),
    ]
