# Generated by Django 4.2 on 2023-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0005_alter_projectmemberreview_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="role",
            field=models.CharField(default="helper", max_length=100),
            preserve_default=False,
        ),
    ]
