# Generated by Django 4.2 on 2023-04-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_projectmember_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="role_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
