# Generated by Django 4.2 on 2023-04-22 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0009_alter_projectrole_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_roles",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
