# Generated by Django 4.2 on 2023-04-22 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_projectrole_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project'),
        ),
    ]
